version: '3.4'

services:
  webapplication1:
    image: webapplication1:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapplication1$
    volumes:
      - D:\outsourcing\devops-technoscreen\devops-technoscreen-workshops\03-docker-aspnetcore\WebApplication1\WebApplication1:C:\app
      - C:\Users\Manuel\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_webapplication1$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapplication1$ bin\\Debug\\netcoreapp2.1\\WebApplication1.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
